In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from warnings import filterwarnings
filterwarnings('ignore')

### connected colab Gpu in vs code

In [2]:
import torch
print("GPU Available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU Name:", torch.cuda.get_device_name(0))


GPU Available: False


In [3]:
df = sns.load_dataset('titanic')

In [4]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True


In [5]:
df.columns


Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [7]:
df.drop(['deck', 'embark_town', 'alive','class','who','adult_male'], axis=1, inplace=True)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  891 non-null    int64  
 1   pclass    891 non-null    int64  
 2   sex       891 non-null    object 
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64  
 5   parch     891 non-null    int64  
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object 
 8   alone     891 non-null    bool   
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 56.7+ KB


In [9]:
df['age'] = pd.to_numeric(df['age'], errors='coerce')
df['age'] = df['age'].fillna(df['age'].mean())

In [10]:
df.dropna(subset=['embarked'], inplace=True)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  889 non-null    int64  
 1   pclass    889 non-null    int64  
 2   sex       889 non-null    object 
 3   age       889 non-null    float64
 4   sibsp     889 non-null    int64  
 5   parch     889 non-null    int64  
 6   fare      889 non-null    float64
 7   embarked  889 non-null    object 
 8   alone     889 non-null    bool   
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 63.4+ KB


In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [13]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,alone
0,0,3,male,22.0,1,0,7.2500,S,False
1,1,1,female,38.0,1,0,71.2833,C,False
2,1,3,female,26.0,0,0,7.9250,S,True
3,1,1,female,35.0,1,0,53.1000,S,False
4,0,3,male,35.0,0,0,8.0500,S,True


In [14]:
df['sex'] = le.fit_transform(df['sex'])
df['embarked'] = le.fit_transform(df['embarked'])

In [15]:
df.astype('float32')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,alone
0,0.0,3.0,1.0,22.000000,1.0,0.0,7.250000,2.0,0.0
1,1.0,1.0,0.0,38.000000,1.0,0.0,71.283302,0.0,0.0
2,1.0,3.0,0.0,26.000000,0.0,0.0,7.925000,2.0,1.0
3,1.0,1.0,0.0,35.000000,1.0,0.0,53.099998,2.0,0.0
4,0.0,3.0,1.0,35.000000,0.0,0.0,8.050000,2.0,1.0
...,...,...,...,...,...,...,...,...,...
886,0.0,2.0,1.0,27.000000,0.0,0.0,13.000000,2.0,1.0
887,1.0,1.0,0.0,19.000000,0.0,0.0,30.000000,2.0,1.0
888,0.0,3.0,0.0,29.699118,1.0,2.0,23.450001,2.0,0.0
889,1.0,1.0,1.0,26.000000,0.0,0.0,30.000000,0.0,1.0


In [16]:
x = df.drop('survived', axis=1)
y = df['survived']

In [17]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [18]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

model.fit(x_train, y_train)

LogisticRegression()

In [19]:
y_pred = model.predict(x_test)

In [20]:
y_pred

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

In [21]:
y_test

,survived
281,0
435,1
39,1
418,0
585,1
...,...
433,0
807,0
25,1
85,1


In [22]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [23]:
accuracy_score(y_test, y_pred)

0.8033707865168539

In [24]:
confusion_matrix(y_test, y_pred)

array([[90, 19],
       [16, 53]])

In [25]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.85      0.83      0.84       109
           1       0.74      0.77      0.75        69

    accuracy                           0.80       178
   macro avg       0.79      0.80      0.79       178
weighted avg       0.81      0.80      0.80       178



In [26]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,alone
0,0,3,1,22.000000,1,0,7.2500,2,False
1,1,1,0,38.000000,1,0,71.2833,0,False
2,1,3,0,26.000000,0,0,7.9250,2,True
3,1,1,0,35.000000,1,0,53.1000,2,False
4,0,3,1,35.000000,0,0,8.0500,2,True
...,...,...,...,...,...,...,...,...,...
886,0,2,1,27.000000,0,0,13.0000,2,True
887,1,1,0,19.000000,0,0,30.0000,2,True
888,0,3,0,29.699118,1,2,23.4500,2,False
889,1,1,1,26.000000,0,0,30.0000,0,True


In [27]:
x_train

,pclass,sex,age,sibsp,parch,fare,embarked,alone
708,1,0,22.000000,0,0,151.5500,2,True
240,3,0,29.699118,1,0,14.4542,0,False
382,3,1,32.000000,0,0,7.9250,2,True
792,3,0,29.699118,8,2,69.5500,2,False
683,3,1,14.000000,5,2,46.9000,2,False
...,...,...,...,...,...,...,...,...
107,3,1,29.699118,0,0,7.7750,2,True
271,3,1,25.000000,0,0,0.0000,2,True
862,1,0,48.000000,0,0,25.9292,2,True
436,3,0,21.000000,2,2,34.3750,2,False


In [28]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [29]:
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [30]:
x_train_scaled, x_test_scaled

(array([[-1.58410418, -1.40530972, -0.59963554, ...,  2.43059683,
          0.58770431,  0.81076671],
        [ 0.8122747 , -1.40530972, -0.01249955, ..., -0.35813533,
         -1.95246446, -1.23340042],
        [ 0.8122747 ,  0.71158691,  0.16296612, ..., -0.49094895,
          0.58770431,  0.81076671],
        ...,
        [-1.58410418, -1.40530972,  1.38312878, ..., -0.12471679,
          0.58770431,  0.81076671],
        [ 0.8122747 , -1.40530972, -0.67589571, ...,  0.04708333,
          0.58770431, -1.23340042],
        [ 0.8122747 ,  0.71158691,  0.23922629, ..., -0.47611594,
          0.58770431,  0.81076671]]),
 array([[ 0.8122747 ,  0.71158691, -0.14207455, ..., -0.49238913,
          0.58770431,  0.81076671],
        [-1.58410418, -1.40530972, -1.20971688, ...,  1.78882298,
          0.58770431, -1.23340042],
        [ 0.8122747 , -1.40530972, -1.20971688, ..., -0.42348235,
         -1.95246446, -1.23340042],
        ...,
        [ 0.8122747 , -1.40530972,  0.62052712, ..., -

In [31]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)

In [32]:
knn.fit(x_train_scaled, y_train)

KNeighborsClassifier()

In [33]:
y_pred_knn = knn.predict(x_test_scaled)

In [34]:
accuracy_score(y_test, y_pred_knn)

0.797752808988764

In [35]:
confusion_matrix(y_test,y_pred_knn)

array([[90, 19],
       [17, 52]])

In [36]:
print(classification_report(y_test, y_pred_knn))

              precision    recall  f1-score   support

           0       0.84      0.83      0.83       109
           1       0.73      0.75      0.74        69

    accuracy                           0.80       178
   macro avg       0.79      0.79      0.79       178
weighted avg       0.80      0.80      0.80       178



In [37]:
from sklearn.naive_bayes import GaussianNB
model_NB = GaussianNB()

In [38]:

model_NB.fit(x_train, y_train)

GaussianNB()

In [39]:
y_pred_NB = model_NB.predict(x_test)
y_pred_NB

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

In [40]:
accuracy_score(y_test, y_pred_NB)

0.7752808988764045

In [41]:
confusion_matrix(y_test,y_pred_NB)

array([[84, 25],
       [15, 54]])

In [42]:
classification_report(y_test, y_pred_NB)

'              precision    recall  f1-score   support\n\n           0       0.85      0.77      0.81       109\n           1       0.68      0.78      0.73        69\n\n    accuracy                           0.78       178\n   macro avg       0.77      0.78      0.77       178\nweighted avg       0.78      0.78      0.78       178\n'

## Creating Decision tree model for Titanic dataset

In [43]:
from sklearn.tree import DecisionTreeClassifier

In [44]:
model_DT = DecisionTreeClassifier(random_state=42)

In [45]:
model_DT.fit(x_train_scaled, y_train)


DecisionTreeClassifier(random_state=42)

In [46]:
y_pred_DT = model_DT.predict(x_test_scaled)
y_pred_DT

array([1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 1])

In [47]:
accuracy_score(y_test, y_pred_DT)

0.7415730337078652

In [48]:
confusion_matrix(y_test,y_pred_DT)

array([[80, 29],
       [17, 52]])

In [49]:
classification_report(y_test, y_pred_DT)

'              precision    recall  f1-score   support\n\n           0       0.82      0.73      0.78       109\n           1       0.64      0.75      0.69        69\n\n    accuracy                           0.74       178\n   macro avg       0.73      0.74      0.74       178\nweighted avg       0.75      0.74      0.74       178\n'

### SVM Model for Titanic

In [50]:
from sklearn.svm import SVC

In [51]:
model_svm = SVC(kernel='rbf', random_state=42)

In [52]:
model_svm.fit(x_train_scaled, y_train)

SVC(random_state=42)

In [53]:
y_pred_svm = model_svm.predict(x_test_scaled)

In [54]:
y_pred_svm

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

In [55]:
accuracy_score(y_test, y_pred_svm)

0.8146067415730337

In [56]:
confusion_matrix(y_test,y_pred_svm)

array([[91, 18],
       [15, 54]])

In [57]:
classification_report(y_test, y_pred_svm)

'              precision    recall  f1-score   support\n\n           0       0.86      0.83      0.85       109\n           1       0.75      0.78      0.77        69\n\n    accuracy                           0.81       178\n   macro avg       0.80      0.81      0.81       178\nweighted avg       0.82      0.81      0.82       178\n'

## Using cross validation

In [58]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,alone
0,0,3,1,22.000000,1,0,7.2500,2,False
1,1,1,0,38.000000,1,0,71.2833,0,False
2,1,3,0,26.000000,0,0,7.9250,2,True
3,1,1,0,35.000000,1,0,53.1000,2,False
4,0,3,1,35.000000,0,0,8.0500,2,True
...,...,...,...,...,...,...,...,...,...
886,0,2,1,27.000000,0,0,13.0000,2,True
887,1,1,0,19.000000,0,0,30.0000,2,True
888,0,3,0,29.699118,1,2,23.4500,2,False
889,1,1,1,26.000000,0,0,30.0000,0,True


In [59]:
x = df.drop('survived', axis=1)
y = df['survived']

In [60]:
from sklearn.model_selection import cross_val_score

In [67]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(x)

In [70]:
scores = cross_val_score(model_svm, X_scaled, y, cv=5)

In [71]:
print(scores)

[0.83146067 0.82022472 0.81460674 0.80898876 0.86440678]
