In [5]:
import numpy as np

x = np.array([[1, 2, 3],
              [4, 5, 6]], dtype=np.float32)

print(x.shape)   # (2 rows, 3 col)
print(x.dtype)   # float32
print(x.ndim)    # 2
print(x.sum(axis=0)) #[5. 7. 9.]
print(x.sum(axis=1)) # [ 6. 15.]

mean = x.mean(axis=0)
print(mean, mean.shape)


(2, 3)
float32
2
[5. 7. 9.]
[ 6. 15.]
[2.5 3.5 4.5] (3,)


In [14]:
import numpy as np

X = np.array([[1,2,3],
              [4,5,6]])

col = X[:,2] 
col = col * 5

print(col)

[15 30]


### Normalization on array

In [18]:
import numpy as np

X = np.array([[70,80,90],
         [60,75,85],
         [90,95,100]])

mean = X.mean(axis=0) # calculating mean
std = X.std(axis=0) # calculating Standard deviation

X_norm = (X - mean)/std # using Normalization formula (Normal Distribution)

# printing result
print("Original Data:\n", X,"\n")
print("Mean:", mean,"\n")
print("Std:", std,"\n")
print("Normalized Data:\n", X_norm,"\n")

#  Verify normalization
print("Mean after normalization:", X_norm.mean(axis=0))
print("Std after normalization:", X_norm.std(axis=0))


Original Data:
 [[ 70  80  90]
 [ 60  75  85]
 [ 90  95 100]] 

Mean: [73.33333333 83.33333333 91.66666667] 

Std: [12.47219129  8.49836586  6.23609564] 

Normalized Data:
 [[-0.26726124 -0.39223227 -0.26726124]
 [-1.06904497 -0.98058068 -1.06904497]
 [ 1.33630621  1.37281295  1.33630621]] 

Mean after normalization: [ 3.70074342e-16  5.18104078e-16 -8.14163551e-16]
Std after normalization: [1. 1. 1.]


In [ ]:
X = np.array([[1,2,3],  
              [4,5,6]])

NameError: name 'np' is not defined